locale: "en-US"
site_theme: "default"
title: "Junteng Liu"
title_separator: "-"
name: &name "Junteng Liu"
description: &description "Junteng Liu's academic homepage"
url: "https://bench-induction-ai.github.io"
baseurl: "/LJT-Homepage"
repository: "bench-induction-ai/LJT-Homepage"

author:
  name: "Junteng Liu"
  bio: "First-year PhD candidate at HKUST NLP Group"
  employer: "Hong Kong University of Science and Technology"
  email: "jliugi@connect.ust.hk"
  googlescholar: "https://scholar.google.com/citations?hl=en&user=tbK9jl4AAAAJ&view_op=list_works&sortby=pubdate"
  github: "Vicent0205"
  twitter: "junteng88716710"

breadcrumbs: false
words_per_minute: 160
future: false
read_more: "disabled"
comments:
  provider: false
atom_feed:
  hide: true

analytics:
  provider: false

include:
  - _pages
exclude:
  - .github
  - _drafts
  - _posts
  - _portfolio
  - _publications
  - _talks
  - _teaching
  - _pages/404.md
  - _pages/archive-layout-with-content.md
  - _pages/category-archive.html
  - _pages/collection-archive.html
  - _pages/cv-json.md
  - _pages/cv.md
  - _pages/markdown.md
  - _pages/non-menu-page.md
  - _pages/page-archive.html
  - _pages/portfolio.html
  - _pages/publications.html
  - _pages/sitemap.md
  - _pages/tag-archive.html
  - _pages/talkmap.html
  - _pages/talks.html
  - _pages/teaching.html
  - _pages/terms.md
  - _pages/year-archive.html
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Dockerfile
  - Gemfile
  - LICENSE
  - README
  - node_modules
  - package.json*
  - vendor

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
markdown: kramdown
highlighter: rouge
excerpt_separator: "\n\n"
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo

collections: {}

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

sass:
  sass_dir: _sass
  style: compressed

permalink: /:categories/:title/
timezone: Etc/UTC

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

compress_html:
  clippings: all
  ignore:
    envs: development
